version: "3.9"

services:
  web:
    build: .
    stdin_open: true
    tty: true
    environment:
      - SITE_POSTGRESQL_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./:/service/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
