"""empty message

Revision ID: 5dcf3e9b3aa6
Revises: 
Create Date: 2023-03-08 00:47:18.871788

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5dcf3e9b3aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_table_id'), 'client_table', ['id'], unique=False)
    op.create_table('price_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'RUB', 'EURO', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_table_id'), 'price_table', ['id'], unique=False)
    op.create_table('product_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['price_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_table_id'), 'product_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_table_id'), table_name='product_table')
    op.drop_table('product_table')
    op.drop_index(op.f('ix_price_table_id'), table_name='price_table')
    op.drop_table('price_table')
    op.drop_index(op.f('ix_client_table_id'), table_name='client_table')
    op.drop_table('client_table')
    # ### end Alembic commands ###
